### PR TITLE
Use Go Modules and remove outdated files

### PR DESCRIPTION
**Pull request by pothos**
Port to Go Modules, regenerate vendor folder, and remove outdated build scripts.

# How to use
```
make # build
make test # run tests
```

# Testing done
```
rm bin/mayday
make # compiles
bin/mayday -h # prints usage
make test # run tests
rm -r vendor
git status # shows missing files
make vendor # regenerate the vendor directory
git status # shows that no changes are done
```

Note: When used in coreos-overlay, the ebuild file needs a change to `COREOS_GO_MOD=vendor go_build "${COREOS_GO_PACKAGE}"` from just `go_build "${COREOS_GO_PACKAGE}"`.

### CODE REVIEW

**Review by t-lo — APPROVED** [review]
Ran the validation steps in "Testing done", works as advertised (though an initial "make vendor" is missing for a fresh check-out).

**Review by dongsupark — COMMENTED** [review]
Go modules part looks good.

Though with this PR, `make test` does not run every test. It simply succeeds without traversing subdirectories.
Also `test` script does not run, as it depends on `build`.

I see 2 options.
1) You can add corresponding subdirectories to the `test` target in Makefile, and remove the existing `test` script.
2) Or you can adapt the `test` script so it works again, and remove the `test` target from Makefile.

**Comment by pothos** [comment]
I've missed the existing `test` script and incorporated it now with a few fixes.

**Review by dongsupark — APPROVED** [review]

**Comment by pothos** [comment]
Oh, wrong default branch…

**Pull request merged**
